; ----------------------------------------------------------------------------------------------------------------
; Kişi      :: Abdulkadir U.
; Tarih     :: 12.08.2025
; Başlık    :: Sil ve Yazdır
; Açıklama  :: Harici macroların yer aldığı dosya
; ----------------------------------------------------------------------------------------------------------------

; ----------------------------------------------------------------------------------------------------------------
; ** INT 10H yardımıyla ekran silmeyi sağlayan macro kodu
; ----------------------------------------------------------------------------------------------------------------
SIL         MACRO
            MOV CX, 0000H                       ; Ekranın sol üst köşesi satır/sütun adresi
            MOV DX, 184FH                       ; Ekranın sağ alt köşesi satır/sütun adresi
            MOV BH, 07H                         ; Öznitelik değeri (Attribute Byte)
            MOV AX, 0600H                       ; AH = 06H pencereyi yukarı kaydır
            INT 10H                             ; 10H numaralı kesmeyi çağır
            ENDM
; ----------------------------------------------------------------------------------------------------------------
; ** INT 21H yardımıyla ekrana mesaj yazdıran macro
; ----------------------------------------------------------------------------------------------------------------
YAZDIR      MACRO text
            LEA DX, text                        ; DX yazdırılacak mesajın başını göstermeli
            MOV AH, 09H                         ; AH = 09H ekrana mesaj yaz
            INT 21H                             ; 21H numaralı kesmeyi çağır
            ENDM